# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: nllb_serve build test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main"]

permissions:
  contents: read

env:
  PYTHONUTF8: "1"
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]      
        python-version: ["3.8", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
    - name: Install module
      run: |
        python3 -m pip install .
    - name: check nllb-serve
      run: |
        nllb-serve -h
    - name: check nllb-batch
      run: |
        nllb-batch -h
        nllb-batch -i <(echo "Hello. This is a test sentence.") -sl eng_Latn -tl kan_Knda
